### PR TITLE
test vs_install and new ami

### PR DESCRIPTION
**Pull request by janeyx99**
for testing purposes

removed quiet flag

### CODE REVIEW

**Comment by seemethere** [comment]
I think getting rid of the `--wait` flag is a bit dangerous since we wouldn't know if the install/uninstall is complete before checking the exitCode

Also their docs include some information on different error codes, https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019#error-codes

**Comment by janeyx99** [comment]
Test complete!

**Comment by seemethere** [comment]
re-opening this to test new AMI

**Comment by janeyx99** [comment]
testing should all be done

**Pull request closed without merging**
